// Code generated by cmd/reset; DO NOT EDIT.

package pool

func (p *Pool[T]) Reset() {
	if p == nil {
		return
	}
	if resetter, ok := any(&p.pool).(interface{ Reset() }); ok {
		resetter.Reset()
	}
}
