package main

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const generatedFile = "reset.gen.go"

var zeroByType = map[string]string{
	"bool":       "false",
	"int":        "0",
	"int8":       "0",
	"int16":      "0",
	"int32":      "0",
	"int64":      "0",
	"uint":       "0",
	"uint8":      "0",
	"uint16":     "0",
	"uint32":     "0",
	"uint64":     "0",
	"uintptr":    "0",
	"float32":    "0",
	"float64":    "0",
	"complex64":  "0",
	"complex128": "0",
	"byte":       "0",
	"rune":       "0",
	"string":     `""`,
	"error":      "nil",
	"any":        "nil",
}

type namedStruct struct {
	name       string
	typeParams string
	typ        *ast.StructType
}

func parsePackage(dir string, entries []os.DirEntry) ([]namedStruct, string, error) {
	fset := token.NewFileSet()
	var structs []namedStruct
	pkgName := ""

	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") || name == generatedFile {
			continue
		}

		f, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, parser.ParseComments)
		if err != nil {
			return nil, "", fmt.Errorf("parse %s: %w", name, err)
		}
		if pkgName == "" {
			pkgName = f.Name.Name
		}
		structs = append(structs, structsFromFile(f)...)
	}

	sort.Slice(structs, func(i, j int) bool { return structs[i].name < structs[j].name })
	return structs, pkgName, nil
}

func structsFromFile(f *ast.File) []namedStruct {
	var out []namedStruct
	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.TYPE {
			continue
		}
		for _, spec := range gd.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}
			if !hasGenerateReset(gd.Doc, ts.Doc, ts.Comment) {
				continue
			}
			out = append(out, namedStruct{
				name:       ts.Name.Name,
				typeParams: typeParamList(ts),
				typ:        st,
			})
		}
	}
	return out
}

func hasGenerateReset(groups ...*ast.CommentGroup) bool {
	for _, g := range groups {
		if g == nil {
			continue
		}
		for _, c := range g.List {
			text := strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(c.Text), "//"))
			if text == "generate:reset" {
				return true
			}
		}
	}
	return false
}

func generateFile(pkgName string, structs []namedStruct) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/reset; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkgName)

	for i, st := range structs {
		if i > 0 {
			b.WriteByte('\n')
		}
		writeResetMethod(&b, st)
	}

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("gofmt: %w\n%s", err, b.String())
	}
	return formatted, nil
}

func typeParamList(ts *ast.TypeSpec) string {
	if ts.TypeParams == nil || len(ts.TypeParams.List) == 0 {
		return ""
	}
	var names []string
	for _, field := range ts.TypeParams.List {
		for _, n := range field.Names {
			names = append(names, n.Name)
		}
	}
	if len(names) == 0 {
		return ""
	}
	return "[" + strings.Join(names, ", ") + "]"
}

func writeResetMethod(b *strings.Builder, st namedStruct) {
	recv := receiverName(st.name)
	fmt.Fprintf(b, "func (%s *%s%s) Reset() {\n", recv, st.name, st.typeParams)
	fmt.Fprintf(b, "	if %s == nil {\n", recv)
	b.WriteString("		return\n")
	b.WriteString("	}\n")

	if st.typ.Fields == nil {
		b.WriteString("}\n")
		return
	}

	for _, field := range st.typ.Fields.List {
		for _, name := range fieldNames(field) {
			writeReset(b, recv+"."+name, field.Type, "	")
		}
	}
	b.WriteString("}\n")
}

func receiverName(typeName string) string {
	for _, r := range typeName {
		return strings.ToLower(string(r))
	}
	return "s"
}

func fieldNames(field *ast.Field) []string {
	if len(field.Names) > 0 {
		names := make([]string, 0, len(field.Names))
		for _, n := range field.Names {
			if n.Name != "_" {
				names = append(names, n.Name)
			}
		}
		return names
	}
	if name := embeddedName(field.Type); name != "" {
		return []string{name}
	}
	return nil
}

func embeddedName(expr ast.Expr) string {
	switch t := unwrap(expr).(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return embeddedName(t.X)
	case *ast.SelectorExpr:
		return t.Sel.Name
	case *ast.IndexExpr:
		return embeddedName(t.X)
	case *ast.IndexListExpr:
		return embeddedName(t.X)
	default:
		return ""
	}
}

func unwrap(expr ast.Expr) ast.Expr {
	for {
		p, ok := expr.(*ast.ParenExpr)
		if !ok {
			return expr
		}
		expr = p.X
	}
}

func writeReset(b *strings.Builder, path string, typ ast.Expr, indent string) {
	switch t := unwrap(typ).(type) {
	case *ast.Ident:
		if z, ok := zeroByType[t.Name]; ok {
			fmt.Fprintf(b, "%s%s = %s\n", indent, path, z)
			return
		}
		writeCallReset(b, "&"+path, indent)

	case *ast.StarExpr:
		fmt.Fprintf(b, "%sif %s != nil {\n", indent, path)
		inner := unwrap(t.X)
		if id, ok := inner.(*ast.Ident); ok {
			if z, ok := zeroByType[id.Name]; ok {
				fmt.Fprintf(b, "%s	*%s = %s\n", indent, path, z)
				fmt.Fprintf(b, "%s}\n", indent)
				return
			}
		}
		fmt.Fprintf(b, "%s	if resetter, ok := any(%s).(interface{ Reset() }); ok {\n", indent, path)
		fmt.Fprintf(b, "%s		resetter.Reset()\n", indent)
		fmt.Fprintf(b, "%s	}\n", indent)
		fmt.Fprintf(b, "%s}\n", indent)

	case *ast.ArrayType:
		if t.Len == nil {
			fmt.Fprintf(b, "%s%s = %s[:0]\n", indent, path, path)
			return
		}
		fmt.Fprintf(b, "%sfor i := range %s {\n", indent, path)
		writeReset(b, path+"[i]", t.Elt, indent+"	")
		fmt.Fprintf(b, "%s}\n", indent)

	case *ast.MapType:
		fmt.Fprintf(b, "%sclear(%s)\n", indent, path)

	case *ast.InterfaceType:
		fmt.Fprintf(b, "%sif resetter, ok := %s.(interface{ Reset() }); ok && %s != nil {\n", indent, path, path)
		fmt.Fprintf(b, "%s	resetter.Reset()\n", indent)
		fmt.Fprintf(b, "%s}\n", indent)

	case *ast.ChanType, *ast.FuncType:
		fmt.Fprintf(b, "%s%s = nil\n", indent, path)

	case *ast.SelectorExpr:
		if astIdentName(t.X) == "unsafe" && t.Sel.Name == "Pointer" {
			fmt.Fprintf(b, "%s%s = nil\n", indent, path)
			return
		}
		writeCallReset(b, "&"+path, indent)

	case *ast.IndexExpr, *ast.IndexListExpr:
		writeCallReset(b, "&"+path, indent)

	default:
		writeCallReset(b, "&"+path, indent)
	}
}

func writeCallReset(b *strings.Builder, addr string, indent string) {
	fmt.Fprintf(b, "%sif resetter, ok := any(%s).(interface{ Reset() }); ok {\n", indent, addr)
	fmt.Fprintf(b, "%s	resetter.Reset()\n", indent)
	fmt.Fprintf(b, "%s}\n", indent)
}

func astIdentName(expr ast.Expr) string {
	id, ok := unwrap(expr).(*ast.Ident)
	if !ok {
		return ""
	}
	return id.Name
}

// used by tests to generate from source without touching the filesystem
func generateFromSource(filename, src string) ([]byte, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, filename, src, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	structs := structsFromFile(f)
	if len(structs) == 0 {
		return nil, nil
	}
	return generateFile(f.Name.Name, structs)
}
