package main

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

const generatedFile = "reset.gen.go"

var zeroByType = map[string]string{
	"bool":       "false",
	"int":        "0",
	"int8":       "0",
	"int16":      "0",
	"int32":      "0",
	"int64":      "0",
	"uint":       "0",
	"uint8":      "0",
	"uint16":     "0",
	"uint32":     "0",
	"uint64":     "0",
	"uintptr":    "0",
	"float32":    "0",
	"float64":    "0",
	"complex64":  "0",
	"complex128": "0",
	"byte":       "0",
	"rune":       "0",
	"string":     `""`,
	"error":      "nil",
	"any":        "nil",
}

type namedStruct struct {
	name       string
	typeParams string
	typ        *ast.StructType
}

func parsePackage(dir string, entries []os.DirEntry) ([]namedStruct, string, error) {
	fset := token.NewFileSet()
	var structs []namedStruct
	pkgName := ""

	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") || name == generatedFile {
			continue
		}

		f, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, parser.ParseComments)
		if err != nil {
			return nil, "", fmt.Errorf("parse %s: %w", name, err)
		}
		if pkgName == "" {
			pkgName = f.Name.Name
		}
		structs = append(structs, structsFromFile(f)...)
	}

	sort.Slice(structs, func(i, j int) bool { return structs[i].name < structs[j].name })
	return structs, pkgName, nil
}

func structsFromFile(f *ast.File) []namedStruct {
	var out []namedStruct
	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.TYPE {
			continue
		}
		for _, spec := range gd.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}
			if !hasGenerateReset(gd.Doc, ts.Doc, ts.Comment) {
				continue
			}
			out = append(out, namedStruct{
				name:       ts.Name.Name,
				typeParams: typeParamList(ts),
				typ:        st,
			})
		}
	}
	return out
}

func hasGenerateReset(groups ...*ast.CommentGroup) bool {
	for _, g := range groups {
		if g == nil {
			continue
		}
		for _, c := range g.List {
			text := strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(c.Text), "//"))
			if text == "generate:reset" {
				return true
			}
		}
	}
	return false
}

const (
	kindAssign     = "assign"
	kindClear      = "clear"
	kindPtr        = "ptr"
	kindArray      = "array"
	kindCallReset  = "callReset"
	kindIfaceReset = "ifaceReset"
)

type fileData struct {
	Package string
	Methods []methodData
}

type methodData struct {
	Recv       string
	TypeName   string
	TypeParams string
	Stmts      []stmt
}

type stmt struct {
	Kind  string
	Path  string
	Value string
	Addr  string
	Inner []stmt
}

var resetTmpl = template.Must(template.New("reset").Parse(`
{{- define "file" -}}
// Code generated by cmd/reset; DO NOT EDIT.

package {{.Package}}
{{range .Methods}}
{{template "method" .}}
{{end}}
{{- end}}

{{- define "method" -}}
func ({{.Recv}} *{{.TypeName}}{{.TypeParams}}) Reset() {
	if {{.Recv}} == nil {
		return
	}
{{range .Stmts}}{{template "stmt" .}}{{end}}}
{{- end}}

{{- define "stmt"}}{{if eq .Kind "assign"}}{{.Path}} = {{.Value}}
{{else if eq .Kind "clear"}}clear({{.Path}})
{{else if eq .Kind "ptr"}}if {{.Path}} != nil {
{{range .Inner}}{{template "stmt" .}}{{end}}}
{{else if eq .Kind "array"}}for i := range {{.Path}} {
{{range .Inner}}{{template "stmt" .}}{{end}}}
{{else if eq .Kind "callReset"}}if resetter, ok := any({{.Addr}}).(interface{ Reset() }); ok {
	resetter.Reset()
}
{{else if eq .Kind "ifaceReset"}}if resetter, ok := {{.Path}}.(interface{ Reset() }); ok && {{.Path}} != nil {
	resetter.Reset()
}
{{end}}{{end}}
`))

func generateFile(pkgName string, structs []namedStruct) ([]byte, error) {
	data := fileData{
		Package: pkgName,
		Methods: make([]methodData, 0, len(structs)),
	}
	for _, st := range structs {
		data.Methods = append(data.Methods, buildMethod(st))
	}

	var b strings.Builder
	if err := resetTmpl.ExecuteTemplate(&b, "file", data); err != nil {
		return nil, fmt.Errorf("template: %w", err)
	}

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("gofmt: %w\n%s", err, b.String())
	}
	return formatted, nil
}

func typeParamList(ts *ast.TypeSpec) string {
	if ts.TypeParams == nil || len(ts.TypeParams.List) == 0 {
		return ""
	}
	var names []string
	for _, field := range ts.TypeParams.List {
		for _, n := range field.Names {
			names = append(names, n.Name)
		}
	}
	if len(names) == 0 {
		return ""
	}
	return "[" + strings.Join(names, ", ") + "]"
}

func buildMethod(st namedStruct) methodData {
	recv := receiverName(st.name)
	m := methodData{
		Recv:       recv,
		TypeName:   st.name,
		TypeParams: st.typeParams,
	}
	if st.typ.Fields == nil {
		return m
	}
	for _, field := range st.typ.Fields.List {
		for _, name := range fieldNames(field) {
			m.Stmts = append(m.Stmts, buildStmts(recv+"."+name, field.Type)...)
		}
	}
	return m
}

func receiverName(typeName string) string {
	for _, r := range typeName {
		return strings.ToLower(string(r))
	}
	return "s"
}

func fieldNames(field *ast.Field) []string {
	if len(field.Names) > 0 {
		names := make([]string, 0, len(field.Names))
		for _, n := range field.Names {
			if n.Name != "_" {
				names = append(names, n.Name)
			}
		}
		return names
	}
	if name := embeddedName(field.Type); name != "" {
		return []string{name}
	}
	return nil
}

func embeddedName(expr ast.Expr) string {
	switch t := unwrap(expr).(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return embeddedName(t.X)
	case *ast.SelectorExpr:
		return t.Sel.Name
	case *ast.IndexExpr:
		return embeddedName(t.X)
	case *ast.IndexListExpr:
		return embeddedName(t.X)
	default:
		return ""
	}
}

func unwrap(expr ast.Expr) ast.Expr {
	for {
		p, ok := expr.(*ast.ParenExpr)
		if !ok {
			return expr
		}
		expr = p.X
	}
}

func buildStmts(path string, typ ast.Expr) []stmt {
	switch t := unwrap(typ).(type) {
	case *ast.Ident:
		if z, ok := zeroByType[t.Name]; ok {
			return []stmt{{Kind: kindAssign, Path: path, Value: z}}
		}
		return []stmt{callReset("&" + path)}

	case *ast.StarExpr:
		inner := unwrap(t.X)
		if id, ok := inner.(*ast.Ident); ok {
			if z, ok := zeroByType[id.Name]; ok {
				return []stmt{{
					Kind:  kindPtr,
					Path:  path,
					Inner: []stmt{{Kind: kindAssign, Path: "*" + path, Value: z}},
				}}
			}
		}
		return []stmt{{Kind: kindPtr, Path: path, Inner: []stmt{callReset(path)}}}

	case *ast.ArrayType:
		if t.Len == nil {
			return []stmt{{Kind: kindAssign, Path: path, Value: path + "[:0]"}}
		}
		return []stmt{{Kind: kindArray, Path: path, Inner: buildStmts(path+"[i]", t.Elt)}}

	case *ast.MapType:
		return []stmt{{Kind: kindClear, Path: path}}

	case *ast.InterfaceType:
		return []stmt{{Kind: kindIfaceReset, Path: path}}

	case *ast.ChanType, *ast.FuncType:
		return []stmt{{Kind: kindAssign, Path: path, Value: "nil"}}

	case *ast.SelectorExpr:
		if astIdentName(t.X) == "unsafe" && t.Sel.Name == "Pointer" {
			return []stmt{{Kind: kindAssign, Path: path, Value: "nil"}}
		}
		return []stmt{callReset("&" + path)}

	case *ast.IndexExpr, *ast.IndexListExpr:
		return []stmt{callReset("&" + path)}

	default:
		return []stmt{callReset("&" + path)}
	}
}

func callReset(addr string) stmt {
	return stmt{Kind: kindCallReset, Addr: addr}
}

func astIdentName(expr ast.Expr) string {
	id, ok := unwrap(expr).(*ast.Ident)
	if !ok {
		return ""
	}
	return id.Name
}

// used by tests to generate from source without touching the filesystem
func generateFromSource(filename, src string) ([]byte, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, filename, src, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	structs := structsFromFile(f)
	if len(structs) == 0 {
		return nil, nil
	}
	return generateFile(f.Name.Name, structs)
}
